slam_toolbox:
  ros__parameters:

    use_sim_time: true

    # LunaBot TF frames
    odom_frame: lunabot/odom
    map_frame: map
    base_frame: lunabot/base_link

    # LiDAR
    scan_topic: /scan

    # SLAM mode
    mode: mapping

    # Map settings
    resolution: 0.05
    min_laser_range: 0.2
    max_laser_range: 12.0
    minimum_time_interval: 0.2
    transform_publish_period: 0.05
    map_update_interval: 2.0

    # Scan processing
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0

    # TF
    transform_timeout: 0.2
    tf_buffer_duration: 30.0

    # Loop closure / scan matching
    use_scan_matching: true
    use_scan_barycenter: true
    do_loop_closing: true

    # Solver
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None